version: "2"

services:
  #######
  # DFS #
  #######
  namenode:
    image: bde2020/hadoop-namenode:1.2.0-hadoop2.8-java8
    container_name: namenode
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    ports:
      - "50070:50070"
    env_file:
      - ./hadoop.env
  
  datanode:
    image: bde2020/hadoop-datanode:1.2.0-hadoop2.8-java8
    container_name: datanode
    depends_on:
      - namenode
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    ports:
      - "50075:50075"
    env_file:
      - ./hadoop.env

  ########
  # YARN #
  ########

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:1.2.0-hadoop2.8-java
    container_name: resourcemanager
    depends_on:
      - namenode
      - datanode
    ports:
      - "8088:8088"
    env_file:
      - ./hadoop.env
  
  nodemanager1:
    image: bde2020/hadoop-nodemanager:1.2.0-hadoop2.8-java8
    container_name: nodemanager1
    depends_on:
      - namenode
      - datanode
    ports:
      - "8042:8042"
    env_file:
      - ./hadoop.env

  historyserver:
    image: bde2020/hadoop-historyserver:1.2.0-hadoop2.8-java8
    container_name: historyserver
    depends_on:
      - namenode
      - datanode
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    ports:
      - "8188:8188"
    env_file:
      - ./hadoop.env

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:

networks:
  hadoop:
    external: true
